{% set version = "1.2.0" %}


package:
  name: ajsonrpc
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/ajsonrpc/ajsonrpc-{{ version }}.tar.gz
  sha256: 791bac18f0bf0dee109194644f151cf8b7ff529c4b8d6239ac48104a3251a19f

build:
  number: 1
  noarch: python
  entry_points:
    - async-json-rpc-server=ajsonrpc.scripts.server:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - ajsonrpc
  commands:
    - pip check
    - async-json-rpc-server --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pavlov99/ajsonrpc
  summary: Async JSON-RPC 2.0 protocol + server powered by asyncio
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hmaarrfk
